version: '3.8'

services:
  # 1. The Database
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # 2. The Message Broker
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # The communication port
      - "15672:15672" # The Dashboard port

    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 3. User Service (Runs on 8000)
  user_service:
    build: ./user_service
    environment:
      - SECRET_KEY=my_super_secret_key
      - ALGORITHM=HS256
    container_name: user_service
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  # 4. Task Service (Runs on 8001)
  task_service:
    build: ./task_service
    environment:
      - SECRET_KEY=my_super_secret_key
      - ALGORITHM=HS256
    container_name: task_service
    ports:
      - "8001:8001"
    depends_on:
      - mongodb
      - rabbitmq

    rabbitmq:
        condition: service_healthy

  # 5. Notification Worker (No ports needed, it runs in background)
  notification_service:
    build: ./notification_service
    container_name: notification_service
    restart: always
    depends_on:
      - rabbitmq

volumes:
  mongo_data: